name: Deploy Translations to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy translations to'
        required: true
        default: 'test'
        options:
          - test
          - production

jobs:
  deploy-translations:
    name: Pull translations from Tolgee and deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to interact with GitHub's OIDC Token endpoint
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts && npm exec allow-scripts run

      - name: Pull translations from Tolgee (production - reviewed only)
        if: inputs.environment == 'production'
        env:
          TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
        run: npx tolgee pull --states REVIEWED

      - name: Pull translations from Tolgee (test - reviewed and translated)
        if: inputs.environment == 'test'
        env:
          TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
        run: npx tolgee pull --states REVIEWED,TRANSLATED

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.JOD_AWS_ACCOUNT_ID }}:role/${{ secrets.JOD_AWS_GITHUB_ROLE_NAME}}
          aws-region: eu-west-1

      - name: Copy translations to S3
        env:
          S3_BUCKET: ${{ secrets.JOD_AWS_DIST_BUCKET }}
        run: |
          aws s3 sync --delete --exclude "*" --include "*.json" --cache-control "public,max-age=0,s-maxage=300,must-revalidate" ./src/i18n/ s3://$S3_BUCKET/yksilo/i18n/
